Pi-hole 2025.03.0

diff --git a/pi-hole/Dockerfile b/pi-hole/Dockerfile
--- a/pi-hole/Dockerfile
+++ b/pi-hole/Dockerfile
@@ -1,47 +1,78 @@
-# Customize upstream image #########################################################################
-FROM	pihole/pihole:2024.07.0 AS pihole
+FROM	pihole/pihole:2025.03.0 AS pihole
 
-SHELL	["/bin/bash", "-o", "pipefail", "-c"]
+ARG	YQ_VERSION=v4.45.1
+ARG	SV_VERSION=0.2
 
-# Check if build args are not empty ################################################################
+SHELL	["/bin/bash", "-e", "-o", "pipefail", "-c"]
+
+# Ensure that build args are given
 ARG	BUILD_ARCH
 ARG	VERSION
 RUN	[ -z "$BUILD_ARCH" ] && echo "Error: Build argument 'BUILD_ARCH' is missing" && exit 1 || true
 RUN	[ -z "$VERSION" ] && echo "Error: Build argument 'VERSION' is missing" && exit 1 || true
 
-# Update base image packages, install jq and cleanup
-RUN	apt-get update && apt-get -y upgrade \
-&&	apt-get -y install jq \
-&&	rm -rf /var/lib/apt/lists/*
+# Update base image packages and install additional software
+RUN <<"EOF"
+	apk upgrade --no-cache
+	apk add     --no-cache dumb-init nginx bash-completion
+EOF
+
+# Install yq
+RUN <<EOF
+	case "$BUILD_ARCH" in
+		armhf)   BUILD_ARCH="arm" ;;
+		aarch64) BUILD_ARCH="arm64" ;;
+		# amd64)   BUILD_ARCH="amd64" ;;
+	esac
+
+	curl -sSLf -o /usr/bin/yq "https://github.com/mikefarah/yq/releases/download/$YQ_VERSION/yq_linux_$BUILD_ARCH"
+	chmod +x /usr/bin/yq
+
+	# Test binary
+	yq --version
+EOF
+
+# Install supervisor.sh
+RUN <<"EOF"
+	curl -sSLf -o /usr/bin/supervisor.sh               "https://raw.githubusercontent.com/casperklein/supervisor.sh/refs/tags/$SV_VERSION/supervisor.sh"
+	curl -sSLf -o /etc/bash_completion.d/supervisor.sh "https://raw.githubusercontent.com/casperklein/supervisor.sh/refs/tags/$SV_VERSION/supervisor-completion.bash"
+	chmod +x /usr/bin/supervisor.sh
+EOF
 
 # Copy root filesystem
 COPY	rootfs /
 
-# Disable x-frame-options for Home Assistant Ingress
-RUN	sedfile -i '/"X-Frame-Options"/ s/DENY/SAMEORIGIN/g' /etc/.pihole/advanced/pihole-admin.conf
-
 # Remove docker-pi-hole update instructions
-RUN	sedfile -i 's|To install updates, <a href="https://github.com/pi-hole/docker-pi-hole#upgrading-persistence-and-customizations" \
-rel="noopener" target="_blank">replace this old container with a fresh upgraded image</a>.||g' /var/www/html/admin/scripts/pi-hole/php/footer.php
+RUN	sedfile -i 's|To install updates, <a href="https://github.com/pi-hole/docker-pi-hole#upgrading-persistence-and-customizations" rel="noopener" target="_blank">replace this old container with a fresh upgraded image</a>.||' /var/www/html/admin/scripts/js/footer.js
 
-RUN	rm /bin/sedfile
+# TODO Remove after https://github.com/pi-hole/pi-hole/pull/6057 is merged and released
+RUN	sedfile -i 's|chown -R pihole:pihole /etc/pihole /var/log/pihole|chown -R pihole:pihole /etc/pihole/ /var/log/pihole/|' /opt/pihole/pihole-FTL-prestart.sh
+
+# Remove obsolete files
+RUN	rm /etc/nginx/http.d/default.conf /usr/bin/sedfile
 
 # Build dnscrypt-proxy from source #################################################################
-FROM	golang:bullseye AS dnscrypt
+FROM	golang:bookworm AS dnscrypt
 
-ENV	GIT_USER="dnscrypt"
-ENV	GIT_REPO="dnscrypt-proxy"
-ENV	GIT_COMMIT="2.1.7"
-ENV	GIT_ARCHIVE="https://github.com/$GIT_USER/$GIT_REPO/archive/$GIT_COMMIT.tar.gz"
-ENV	DEBIAN_FRONTEND=noninteractive
+ARG	DNSCRYPT_VERSION="2.1.7"
+ENV	URL="https://github.com/dnscrypt/dnscrypt-proxy/archive/$DNSCRYPT_VERSION.tar.gz"
 
+ENV	DEBIAN_FRONTEND="noninteractive"
 RUN	apt-get update && apt-get -y upgrade
 
-WORKDIR	/$GIT_REPO
-ADD	$GIT_ARCHIVE /
-RUN	tar --strip-component 1 -xzvf /$GIT_COMMIT.tar.gz && rm /$GIT_COMMIT.tar.gz
-WORKDIR	/$GIT_REPO/dnscrypt-proxy
+WORKDIR	/build
+RUN	curl -sSLf "$URL" | tar --strip-component 1 -xz
+WORKDIR	/build/dnscrypt-proxy
+
+# Compile with static linking (including all library code in the binary); needed for alpine image
+# Otherwise --> /dnscrypt-proxy: cannot execute: required file not found
+ENV	CGO_ENABLED=0
+
+# Builds a Go binary without symbol tables and debugging information, reducing the file size.
 RUN	go build -ldflags="-s -w" -mod vendor
+
+# Test binary
+RUN	./dnscrypt-proxy -version
 
 # Build final image ################################################################################
 FROM	scratch
@@ -59,25 +90,30 @@ LABEL	image="casperklein/homeassistant-pihole:${VERSION}"
 LABEL	maintainer="Casper Klein"
 LABEL	url="https://github.com/casperklein/homeassistant-addons/tree/master/pi-hole"
 
+# Disable Pi-hole authentication --> Single Sign On via HA Ingress
+ENV	FTLCONF_webserver_api_password=""
+
+# Disable DHCP
+ENV	FTLCONF_dhcp_active="false"
+
+COPY	--from=dnscrypt /build/dnscrypt-proxy/dnscrypt-proxy /usr/bin/
+COPY	--from=pihole / /
+
+ENTRYPOINT ["/usr/bin/dumb-init", "--"]
+CMD	[ "/usr/bin/supervisor.sh", "--config", "/etc/supervisor.yaml" ]
+
 # From base image
 # docker-image-options pihole/pihole:latest | sort | grep -v LABEL
-ENTRYPOINT ["/s6-init"]
+
+# ENTRYPOINT ["start.sh"]
 ENV DNSMASQ_USER="pihole"
 ENV FTL_CMD="no-daemon"
-ENV FTLCONF_LOCAL_IPV4="0.0.0.0"
-ENV IPv6="True"
-ENV PATH="/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
-ENV PHP_ERROR_LOG="/var/log/lighttpd/error-pihole.log"
-ENV phpver="php"
-ENV S6_BEHAVIOUR_IF_STAGE2_FAILS="2"
-ENV S6_CMD_WAIT_FOR_SERVICES_MAXTIME="0"
-ENV S6_KEEP_ENV="1"
+EXPOSE 123/udp
+EXPOSE 443/tcp
 EXPOSE 53/tcp
 EXPOSE 53/udp
-EXPOSE 67/udp
+# EXPOSE 67/udp
 EXPOSE 80/tcp
-HEALTHCHECK CMD dig +short +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1
-SHELL ["/bin/bash","-c"]
-
-COPY	--from=dnscrypt /dnscrypt-proxy/dnscrypt-proxy/dnscrypt-proxy /
-COPY	--from=pihole / /
+# Healthcheck is disabled, to avoid waiting 30s (until container is healthy) to access Pi-hole via HA Ingress
+# HEALTHCHECK CMD dig +short +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1
+WORKDIR /
